### PR TITLE
Pi core

### PR DESCRIPTION
**Pull request by paul-1**
Updates to Core-Scripts for piCore

### CODE REVIEW

**Comment by clbr** [comment]
"rcS: Add a screen clear before starting tc-config" seems to be wrong, it removes clear, not adds?

**Comment by paul-1** [comment]
You are correct, I was reading a note from Juanito and made the wrong change.  I removed that commit.

**Comment by paul-1** [comment]
I forgot that bootlocal.sh is part of Core-Scripts, and forgot to make those changes.  it has been in piCore bootlocal for sometime.

But if you prefer, we can just add it at the end of tc-config.

**Comment by juanitotc** [comment]
Ah - I hadn’t realised  it was in bootlocal , I guess that’s ok then

**Comment by paul-1** [comment]
I'll get a change to bootlocal pushed up.

I think we should only include the governor setting and openssh startup.  I don't know why the serial console was started by default.   Not sure where we should track the config.txt and cmdline.txt   There are somethings in there (That are in piCore11) that need fixed

**Comment by juanitotc** [comment]
I agree for the governor and openssh in bootlocal - I can't comment for the serial console as I've never used it, do many users use it?

I'm OK for tracking config.txt and cmdline.txt in the picore branch.

**Pull request merged**
