### PR TITLE
support ntfs3

### PR DESCRIPTION
**Pull request by aswjh**

### CODE REVIEW

**Comment by clbr** [comment]
Please put the modprobe and which checks inside the function, otherwise it would slow down on non-ntfs computers.

**Comment by clbr** [comment]
Also, I think mount does a modprobe internally if you say "-t ntfs3" and it's not loaded (please test).

**Comment by aswjh** [comment]
'mount -t ntfs3' return 0, but 'mount -t xxx' return 0 too.
Is there another way?

**Comment by clbr** [comment]
What are you trying to detect? You can rely on the ntfs3 module always being on the system.

**Comment by aswjh** [comment]
Detect if kernel support ntfs3

**Comment by clbr** [comment]
It always does. This commit will only be applied to future versions.

**Pull request merged**
