### PR TITLE
Cleaning up some time consuming function (loop)

### PR DESCRIPTION
**Pull request by alphons**
Old rebuildfstab
real    0m 0.47s
user    0m 0.08s
sys     0m 0.38s

New rebuildfstab
real    0m 0.14s
user    0m 0.03s
sys     0m 0.08s

Also the relatime was missing on the ext4 fstype.

### CODE REVIEW

**Comment by clbr** [comment]
Thank you for the patch. While your numbers look good, it would change the behavior, and possibly have speed regressions in some envs. The current code supports manual fstab entries, while this patch would add those a second time. Running blkid without any options does a slow scan, which with optical drives and floppies can be slow (I'm not sure if the -s option also triggers this - it's possible that also does a scan).

Perhaps a large part of the time taken is by the "find" command, where adding "-maxdepth 2" may give some speedup.

If you'd like to submit the ext4 change separately, please do.

**Comment by clbr** [comment]
Oh, about the header edits: removing the includes also may change behavior, and the header comment seems improper when no other contributors have been added therein.

**Comment by alphons** [comment]
-  it would change the behavior NO
- "The current code supports manual fstab entries, while this patch would add those a second time" Also NO, this update does exactly what the other code does, only better and faster
- "blkid without any options does a slow scan", NO, have a look at the source code.
- "with optical drives and floppies can be slow", sure also the NFS mounts can be slow.
- "The current code supports manual fstab entries, while this patch would add those a second time" NO. The behaviour of this code is exactly the same.
- "If you'd like to submit the ext4 change separately, please do." NO, it is all or Nothing, but I get the picture already.

To bad, this code review does not have the high quality i want.

- "removing the includes also may change behavior" NO, no functions are used from the header includes
-  "header comment seems improper when no other contributors have been added therein" NO, I want some more comment, what the script does exactly and so on, this is a start
-

**Comment by clbr** [comment]
Very well, closing this. "come back with better comments" when your patch is wrong is simply rude.

**Comment by Misalf-git** [comment]
I'm angry now, thanks.

**Pull request closed without merging**
