### PR TITLE
Add support for disk search in pretce

### PR DESCRIPTION
**Pull request by CardealRusso**
A fork of find_mountpoint is welcome, as the current one is very sensitive to changes.
Pretce starts to behave like /home, with a fixed directory.

### CODE REVIEW

**Comment by clbr** [comment]
Please squash these into one commit when you think it's ready for review.

**Comment by CardealRusso** [comment]
> Please squash these into one commit when you think it's ready for review.
it's ready for review,  however i have no idea how to squash on github web

**Comment by clbr** [comment]
You can do it on the command line, and then force push.

**Comment by CardealRusso** [comment]
i believe its  done

**Comment by clbr** [comment]
- please also edit the commit message
- the addition of the /pretce dir name would break existing setups
- instead of "! mounted &&", I'd prefer "mounted ||"

The bootcode seems designed to include the dir name. "pretce=sda1/mydir".

**Pull request closed without merging**
