### PR TITLE
Updates tce-load tc-function

### PR DESCRIPTION
**Pull request by polikuo**
tce-load discussion: https://forum.tinycorelinux.net/index.php/topic,26381.0.html
tc-function getBuild() copied from current piCore 14.1

### CODE REVIEW

**Comment by clbr** [comment]
The master branch scripts aren't used on picore, they are on their own branch. Applied the first one. If you want to change picore's detection, please put that change on the picore branch and create a new PR.

**Comment by paul-1** [comment]
The piCore branch is dated.  I have a bunch of things to pull over to make it current with the 14.0.1 release.   That will pickup the getBuild updates.  This is my staged branch of what is in piCore 14.0.1

https://github.com/paul-1/Core-scripts/commits/piCore

The primary differences are
1) micropython based boot loading script.
2) Boot partition stuff.
3) Tweaked tc-config 

But otherwise I've pulled commits from the master branch in.

**Comment by polikuo** [comment]
OK, sorry for the noise.
Is there any way to undo my last commit ?

**Comment by paul-1** [comment]
Its fine,  I'll pull it in when I do the mass update to the piCore branch.

**Pull request closed without merging**
