### PR TITLE
Use utf8 to adapt to various languages

### PR DESCRIPTION
**Pull request by aswjh**

### CODE REVIEW

**Comment by clbr** [comment]
Sorry, I think this is a bad default. FAT filesystems are usually created in the local codepage, not utf8.

**Comment by aswjh** [comment]
In non-English cases, the current default value leads to garbled characters and must be adjusted manually. I think it will affect the newbie experience. Is there a better way?

**Comment by clbr** [comment]
On Wed, 16 Feb 2022 23:09:47 -0800
aswjh ***@***.***> wrote:

> In non-English cases, the current default value leads to garbled characters and must be adjusted manually. I think it will affect the newbie experience. Is there a better way?

I am non-English myself, and utf8 as default would break for me. In
North and East Europe, the codepages are more common than utf8.

It can't really be autodetected, I'm afraid.

**Comment by aswjh** [comment]
What if iocharset is defined by $LANG?

**Comment by clbr** [comment]
Yes, if the user is using an utf-8 locale, "locale charmap" saying so,
then it is fine to mount vfat utf8.

**Comment by aswjh** [comment]
If the default G_FILENAME_ENCODING value is inconsistent with the set iocharset value, garbled characters will still occur in the gtk program

**Comment by aswjh** [comment]
How about adding charmap to cmdline? This can use charmap to set G_FILENAME_ENCODING and iocharset

**Comment by aswjh** [comment]
Also, executing "locale charmap" before mylocale loads, does not get the desired result. Maybe use LANG

**Comment by clbr** [comment]
***@***.***
is usually used when a locale is set. Not manually setting it.

You can't determine the charmap from the LANG name alone, because many
of those don't include the charmap in the name. Bootcode would be bad,
since there are many different charmaps in many different settings, it
would break expectations and be unsure where it applies.

**Comment by aswjh** [comment]
Set iocharset utf8 only for the part of $LANG that ends with utf8，should be no problem.

UTF8=""
[ "${LANG##*.}" == "utf8" ] && UTF8="y"


OPTIONS="${OPTIONS}${UTF8:+,utf8}

**Comment by clbr** [comment]
No, there are locales that use utf8 without having it in the name. And
locales that have capital UTF8, etc etc.

**Comment by aswjh** [comment]
Currently deal with those with utf8 first, if there is no better way.

**Comment by clbr** [comment]
Sorry, that'd be a bad partial solution. Not applicable.

**Comment by aswjh** [comment]
Even so, I think it can support a wider range of languages than the original way, and newbies using non-English don't have to do some troublesome operations. Of course, would love to see a better implementation.

**Pull request closed without merging**
